version: '3.8'

services:
  smashshack:
    build: .
    container_name: smashshack_website
    ports:
      - "8080:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
