server {
    listen 80;
    server_name tv.lilsmash.com;

    location / {
        root /usr/share/nginx/html/tv.lilsmash.com;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name lilsmash.com www.lilsmash.com _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}
